POST http://localhost:3000/api/wordlist/ 
content-type: application/json

{
    "name": "sample",
    "words":["wordA", "wordB", "wordC"],
    "desc": "this is a desc!"
}

###

GET http://localhost:3000/api/wordlist/6503cc2e11a2410e548faa12

###

GET http://localhost:3000/api/wordlist/6508b7f4080f67cc7c52947e

###

GET http://localhost:3000/api/word/getWord/

###
POST http://localhost:3000/api/word/verify/
content-type: application/json

{
   "userInput": "sharkie"
}

### display score
GET http://localhost:3000/api/word/score


###
GET https://api.dictionaryapi.dev/api/v2/entries/en/hello